#pragma once

#include <driver/i2c.h>
#include <esp_log.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <stdio.h>
#include "ssd1306.h"
#include "assets/face.h"
#include "mpu6050.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "esp_timer.h"
#include "shared.h"
#include "math.h"

// --- SSD1306 Commands and Constants ---
#define SSD1306_WIDTH          128
#define SSD1306_HEIGHT         64
#define SSD1306_CMD_MODE       0x00     // Co = 0, D/C = 0
#define SSD1306_DATA_MODE      0x40     // Co = 0, D/C = 1

// Full list of initialization commands for a 128x64 display
static const uint8_t init_cmds[] = {
    0xAE,          // 0xAE: Display OFF
    0xD5, 0x80,    // 0xD5: Set Display Clock Divide Ratio / Oscillator Frequency
    0xA8, 0x3F,    // 0xA8: Set Multiplex Ratio (63 for 64 height)
    0xD3, 0x00,    // 0xD3: Set Display Offset (no offset)
    0x40,          // 0x40: Set Start Line (line 0)
    0x8D, 0x14,    // 0x8D: Charge Pump Setting (VCC generated by internal DC/DC)
    0x20, 0x00,    // 0x20: Set Memory Addressing Mode (Horizontal Addressing Mode)
    0xA1,          // 0xA1: Set Segment Re-map (Horizontal flip)
    0xC8,          // 0xC8: Set COM Output Scan Direction (Vertical flip)
    0xDA, 0x12,    // 0xDA: Set COM Pins Hardware Configuration
    0x81, 0xCF,    // 0x81: Set Contrast Control
    0xD9, 0xF1,    // 0xD9: Set Pre-charge Period
    0xDB, 0x40,    // 0xDB: Set VCOMH Deselect Level
    0xA4,          // 0xA4: Entire Display ON (A5: All pixels ON)
    0xA6,          // 0xA6: Normal Display (A7: Inverse Display)
    0x2E,          // 0x2E: Deactivate Scroll
    0xAF           // 0xAF: Display ON
};

// Simple 8x8 font data for 'H', 'E', 'L', 'O', ',', ' ', 'E', 'S', 'P', '3', '2', '!'
// Each character is 8 bytes (1 page column)

#include "assets/font.h"

// Helper function to map ASCII characters to the custom font array index
int char_to_font_index(char c) {
    return c; // Default to space
}

#define SSD1306_I2C_ADDR 0x3C

/**
 * @brief Send a command to the SSD1306.
 * The command byte is sent right after the Control Byte (0x00 for command mode).
 */
static esp_err_t ssd1306_send_command(uint8_t command) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    
    // Address + Write Bit
    i2c_master_write_byte(cmd, (SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true); 
    
    // Control Byte: Command Mode (0x00)
    i2c_master_write_byte(cmd, SSD1306_CMD_MODE, true);
    
    // Command Byte
    i2c_master_write_byte(cmd, command, true);
    
    i2c_master_stop(cmd);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, cmd, 100 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
    return ret;
}

/**
 * @brief Send a block of data to the SSD1306 GDDRAM.
 * The data block is preceded by the Control Byte (0x40 for data mode).
 */
static esp_err_t ssd1306_send_data(const uint8_t *data, size_t len) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    
    // Address + Write Bit
    i2c_master_write_byte(cmd, (SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    
    // Control Byte: Data Mode (0x40)
    i2c_master_write_byte(cmd, SSD1306_DATA_MODE, true);
    
    // Data Block
    i2c_master_write(cmd, (uint8_t *)data, len, true);
    
    i2c_master_stop(cmd);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, cmd, 100 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
    return ret;
}


/**
 * @brief Initialize the SSD1306 with the necessary command sequence.
 */
static esp_err_t ssd1306_init(void) {
    ESP_LOGI(TAG, "Starting SSD1306 initialization...");
    esp_err_t ret = ESP_OK;
    for (int i = 0; i < sizeof(init_cmds); i++) {
        // Some commands are two bytes long (command + argument), 
        // they are already grouped in the init_cmds array.
        if (ret != ESP_OK) break;
        ret = ssd1306_send_command(init_cmds[i]);
    }
    if (ret == ESP_OK) {
        ESP_LOGI(TAG, "SSD1306 initialized successfully.");
    } else {
        ESP_LOGE(TAG, "SSD1306 initialization failed: %s", esp_err_to_name(ret));
    }

    return ret;
}

/**
 * @brief Clears the entire GDDRAM by sending zeroed data to all pages.
 */
static esp_err_t ssd1306_clear(void) {
    esp_err_t ret = ESP_OK;
    
    // The screen is 8 pages high (64 pixels / 8 bits per page = 8 pages)
    for (uint8_t page = 0; page < (SSD1306_HEIGHT / 8); page++) {
        // 1. Set Page Address (0xB0 | page_num)
        ret = ssd1306_send_command(0xB0 | page); 
        if (ret != ESP_OK) return ret;

        // 2. Set Lower Column Start Address (0x00)
        ret = ssd1306_send_command(0x00);
        if (ret != ESP_OK) return ret;

        // 3. Set Higher Column Start Address (0x10)
        ret = ssd1306_send_command(0x10);
        if (ret != ESP_OK) return ret;
        
        // Create an array of 128 zero bytes for one page
        uint8_t clear_page_data[SSD1306_WIDTH] = {0}; 
        
        // 4. Send the 128 zero bytes to clear the page
        ret = ssd1306_send_data(clear_page_data, SSD1306_WIDTH);
        if (ret != ESP_OK) return ret;
    }
    return ESP_OK;
}

/**
 * @brief Writes a string to the display starting at a specific page (row) and column.
 * It uses the simple 8x8 font defined above.
 * @param str The string to display.
 * @param page The starting page (0-7 for 64-pixel height).
 * @param col The starting column (0-127).
 */
static esp_err_t ssd1306_write_text(const char *str, uint8_t page, uint8_t col) {
    esp_err_t ret = ESP_OK;
    if (page >= (SSD1306_HEIGHT / 8)) return ESP_FAIL; // Invalid page

    // 1. Set Page Address (row)
    ret = ssd1306_send_command(0xB0 | page); 
    if (ret != ESP_OK) return ret;

    // 2. Set Column Address (col)
    // The column address is split into lower (0x00-0x0F) and higher (0x10-0x1F) nibbles
    ret = ssd1306_send_command(0x00 | (col & 0x0F));     // Lower nibble of column start address
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0x10 | (col >> 4));      // Higher nibble of column start address
    if (ret != ESP_OK) return ret;

    // 3. Write data for each character
    for (const char *p = str; *p; p++) {
        int index = char_to_font_index(*p);
        const uint8_t *char_data = font8x8[index];
        // Each character is 8 bytes of data (one column in GDDRAM)
        ret = ssd1306_send_data(char_data, 8); 
        if (ret != ESP_OK) return ret;
    }
    return ESP_OK;
}

static esp_err_t ssd1306_draw_buffer(const uint8_t *buffer) {
    esp_err_t ret = ESP_OK;

    // 1. Set Column Address Range (0 - 127)
    // This tells the SSD1306 to treat the next data as columns 0 through 127
    ret = ssd1306_send_command(0x21); 
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0);    // Start Column
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(127);  // End Column
    if (ret != ESP_OK) return ret;

    // 2. Set Page Address Range (0 - 7)
    // This tells the SSD1306 to treat the next data as pages 0 through 7
    ret = ssd1306_send_command(0x22); 
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0);    // Start Page
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(7);    // End Page
    if (ret != ESP_OK) return ret;

    // 3. Send the buffer in chunks
    // We send 1024 bytes. We could try sending it all at once, but I2C hardware 
    // buffers usually prefer smaller chunks. We will send 128 bytes (1 page) at a time.
    for (int i = 0; i < 1024; i += 128) {
        ret = ssd1306_send_data(&buffer[i], 128);
        if (ret != ESP_OK) return ret;
    }

    return ESP_OK;
}

// Color: 1 = White (On), 0 = Black (Off)
static inline void ssd1306_draw_pixel(uint8_t *buffer, int x, int y, int color) {
    if (x < 0 || x >= SSD1306_WIDTH || y < 0 || y >= SSD1306_HEIGHT) {
        return; // Out of bounds
    }

    if (color) {
        buffer[x + (y / 8) * SSD1306_WIDTH] |= (1 << (y % 8));
    } else {
        buffer[x + (y / 8) * SSD1306_WIDTH] &= ~(1 << (y % 8));
    }
}   

static inline void ssd1306_draw_line(uint8_t *buffer, int x0, int y0, int x1, int y1, int color) {
    int dx = abs(x1 - x0);
    int dy = abs(y1 - y0);
    int sx = (x0 < x1) ? 1 : -1;
    int sy = (y0 < y1) ? 1 : -1;
    int err = dx - dy;

    while (1) {
        ssd1306_draw_pixel(buffer, x0, y0, color);
        if (x0 == x1 && y0 == y1) break;
        int e2 = 2 * err;
        if (e2 > -dy) {
            err -= dy;
            x0 += sx;
        }
        if (e2 < dx) {
            err += dx;
            y0 += sy;
        }
    }
}

// Lined (Hollow) Circle
static inline void ssd1306_draw_circle(uint8_t *buffer, int x0, int y0, int r, int color) {
    int f = 1 - r;
    int ddF_x = 1;
    int ddF_y = -2 * r;
    int x = 0;
    int y = r;

    ssd1306_draw_pixel(buffer, x0, y0 + r, color);
    ssd1306_draw_pixel(buffer, x0, y0 - r, color);
    ssd1306_draw_pixel(buffer, x0 + r, y0, color);
    ssd1306_draw_pixel(buffer, x0 - r, y0, color);

    while (x < y) {
        if (f >= 0) {
            y--;
            ddF_y += 2;
            f += ddF_y;
        }
        x++;
        ddF_x += 2;
        f += ddF_x;

        ssd1306_draw_pixel(buffer, x0 + x, y0 + y, color);
        ssd1306_draw_pixel(buffer, x0 - x, y0 + y, color);
        ssd1306_draw_pixel(buffer, x0 + x, y0 - y, color);
        ssd1306_draw_pixel(buffer, x0 - x, y0 - y, color);
        ssd1306_draw_pixel(buffer, x0 + y, y0 + x, color);
        ssd1306_draw_pixel(buffer, x0 - y, y0 + x, color);
        ssd1306_draw_pixel(buffer, x0 + y, y0 - x, color);
        ssd1306_draw_pixel(buffer, x0 - y, y0 - x, color);
    }
}

// Filled Circle
static inline void ssd1306_fill_circle(uint8_t *buffer, int x0, int y0, int r, int color) {
    int f = 1 - r;
    int ddF_x = 1;
    int ddF_y = -2 * r;
    int x = 0;
    int y = r;

    ssd1306_draw_line(buffer, x0 - r, y0, x0 + r, y0, color);

    while (x < y) {
        if (f >= 0) {
            y--;
            ddF_y += 2;
            f += ddF_y;
        }
        x++;
        ddF_x += 2;
        f += ddF_x;

        ssd1306_draw_line(buffer, x0 - x, y0 + y, x0 + x, y0 + y, color);
        ssd1306_draw_line(buffer, x0 - x, y0 - y, x0 + x, y0 - y, color);
        ssd1306_draw_line(buffer, x0 - y, y0 + x, x0 + y, y0 + x, color);
        ssd1306_draw_line(buffer, x0 - y, y0 - x, x0 + y, y0 - x, color);
    }
}

// Lined Rectangle
static inline void ssd1306_draw_rect(uint8_t *buffer, int x, int y, int w, int h, int color) {
    ssd1306_draw_line(buffer, x, y, x + w - 1, y, color);         // Top
    ssd1306_draw_line(buffer, x, y + h - 1, x + w - 1, y + h - 1, color); // Bottom
    ssd1306_draw_line(buffer, x, y, x, y + h - 1, color);         // Left
    ssd1306_draw_line(buffer, x + w - 1, y, x + w - 1, y + h - 1, color); // Right
}

// Filled Rectangle
static inline void ssd1306_fill_rect(uint8_t *buffer, int x, int y, int w, int h, int color) {
    for (int i = 0; i < h; i++) {
        ssd1306_draw_line(buffer, x, y + i, x + w - 1, y + i, color);
    }
}

// Helper for Rounded Rectangles (draws circle quadrants)
static inline void draw_circle_helper(uint8_t *buffer, int x0, int y0, int r, uint8_t cornername, int color) {
    int f = 1 - r;
    int ddF_x = 1;
    int ddF_y = -2 * r;
    int x = 0;
    int y = r;

    while (x < y) {
        if (f >= 0) {
            y--;
            ddF_y += 2;
            f += ddF_y;
        }
        x++;
        ddF_x += 2;
        f += ddF_x;
        if (cornername & 0x4) { // Top Right
            ssd1306_draw_pixel(buffer, x0 + x, y0 - y, color);
            ssd1306_draw_pixel(buffer, x0 + y, y0 - x, color);
        }
        if (cornername & 0x2) { // Top Left
            ssd1306_draw_pixel(buffer, x0 - x, y0 - y, color);
            ssd1306_draw_pixel(buffer, x0 - y, y0 - x, color);
        }
        if (cornername & 0x8) { // Bottom Right
            ssd1306_draw_pixel(buffer, x0 + x, y0 + y, color);
            ssd1306_draw_pixel(buffer, x0 + y, y0 + x, color);
        }
        if (cornername & 0x1) { // Bottom Left
            ssd1306_draw_pixel(buffer, x0 - x, y0 + y, color);
            ssd1306_draw_pixel(buffer, x0 - y, y0 + x, color);
        }
    }
}

// Helper for Filled Rounded Rectangles
static inline void fill_circle_helper(uint8_t *buffer, int x0, int y0, int r, uint8_t cornername, int delta, int color) {
    int f = 1 - r;
    int ddF_x = 1;
    int ddF_y = -2 * r;
    int x = 0;
    int y = r;

    while (x < y) {
        if (f >= 0) {
            y--;
            ddF_y += 2;
            f += ddF_y;
        }
        x++;
        ddF_x += 2;
        f += ddF_x;

        if (cornername & 0x1) { // Right Half
            ssd1306_draw_line(buffer, x0 + x, y0 - y, x0 + x, y0 + y + delta, color);
            ssd1306_draw_line(buffer, x0 + y, y0 - x, x0 + y, y0 + x + delta, color);
        }
        if (cornername & 0x2) { // Left Half
            ssd1306_draw_line(buffer, x0 - x, y0 - y, x0 - x, y0 + y + delta, color);
            ssd1306_draw_line(buffer, x0 - y, y0 - x, x0 - y, y0 + x + delta, color);
        }
    }
}

// Rounded Rectangle (Lined)
static inline void ssd1306_draw_round_rect(uint8_t *buffer, int x, int y, int w, int h, int r, int color) {
    // Top
    ssd1306_draw_line(buffer, x + r, y, x + w - r - 1, y, color);
    // Bottom
    ssd1306_draw_line(buffer, x + r, y + h - 1, x + w - r - 1, y + h - 1, color);
    // Left
    ssd1306_draw_line(buffer, x, y + r, x, y + h - r - 1, color);
    // Right
    ssd1306_draw_line(buffer, x + w - 1, y + r, x + w - 1, y + h - r - 1, color);

    // Four corners
    draw_circle_helper(buffer, x + r, y + r, r, 2, color);
    draw_circle_helper(buffer, x + w - r - 1, y + r, r, 4, color);
    draw_circle_helper(buffer, x + w - r - 1, y + h - r - 1, r, 8, color);
    draw_circle_helper(buffer, x + r, y + h - r - 1, r, 1, color);
}

/**
 * @brief Draws an Arc with thickness and round caps.
 * @param buffer Screen buffer
 * @param cx Center X
 * @param cy Center Y
 * @param r Radius
 * @param start_angle Start angle in degrees (0 is right, 90 is bottom, etc.)
 * @param end_angle End angle in degrees
 * @param thickness Thickness of the line
 * @param color 1 for White, 0 for Black
 */
static inline void ssd1306_draw_arc(uint8_t *buffer, int cx, int cy, int r, int start_angle, int end_angle, int thickness, int color) {
    // Convert degrees to radians
    float start_rad = start_angle * M_PI / 180.0f;
    float end_rad = end_angle * M_PI / 180.0f;
    
    // Calculate step size based on radius to ensure no gaps (over-sampling)
    // 1 pixel step = 1 / Radius radians
    float step = 1.0f / r; 

    // Handle wrap-around or direction
    if (start_rad > end_rad) {
        // Swap if start > end, or handle logic for crossing 0 if needed
        // For simplicity here, we assume drawing clockwise or simple sweep
    }

    // Brush radius
    int brush_r = thickness / 2;
    if (brush_r < 1) brush_r = 1;

    for (float theta = start_rad; theta <= end_rad; theta += step) {
        // Polar to Cartesian
        int px = cx + (int)(cos(theta) * r);
        int py = cy + (int)(sin(theta) * r);

        // Draw the brush (filled circle) at this point
        // This handles both the thickness and the rounded ends
        ssd1306_fill_circle(buffer, px, py, brush_r, color);
    }
}

static inline void ssd1306_fill_round_rect(uint8_t *buffer, int x, int y, int w, int h, int r, int color) {
    // Basic check for valid radius
    if (r <= 0 || r > w / 2 || r > h / 2) {
        // Fallback to a normal filled rectangle if the radius is invalid
        ssd1306_fill_rect(buffer, x, y, w, h, color);
        return;
    }

    // 1. Draw the Central Vertical Bar
    // This fills the entire height (h) but reduces the width by 2*r.
    // It covers the central flat portion of the sides.
    ssd1306_fill_rect(buffer, x + r, y, w - 2 * r, h, color);

    // 2. Draw the Central Horizontal Bar
    // This fills the entire width (w) but reduces the height by 2*r.
    // This overlaps with step 1 and ensures the flat top and bottom are filled.
    ssd1306_fill_rect(buffer, x, y + r, w, h - 2 * r, color);

    // 3. Draw the Four Filled Circles (The Corners)
    // The centers of the four quarter-circles are located at the corners 
    // of the inner W-2r x H-2r rectangle. These circles perfectly fill 
    // the four corner regions missed by the two central bars.
    
    // Top Left Corner
    ssd1306_fill_circle(buffer, x + r, y + r, r, color);
    
    // Top Right Corner
    ssd1306_fill_circle(buffer, x + w - r - 1, y + r, r, color);
    
    // Bottom Left Corner
    ssd1306_fill_circle(buffer, x + r, y + h - r - 1, r, color);
    
    // Bottom Right Corner
    ssd1306_fill_circle(buffer, x + w - r - 1, y + h - r - 1, r, color);
}

#include <stdlib.h> // For abs()

/**
 * @brief Draws a solid heart shape using circles, rectangles, and lines.
 * * @param buffer Screen buffer (1024 bytes)
 * @param cx Center X coordinate of the heart's bounding box
 * @param cy Center Y coordinate of the heart's bounding box
 * @param size Controls the overall scale (height) of the heart
 * @param color 1 for White, 0 for Black
 */
void ssd1306_draw_heart(uint8_t *buffer, int cx, int cy, int size, int color) {
    if (size < 6) size = 6; // Set a reasonable minimum size

    // 1. Define Geometry
    int r = size / 3;            // Radius of the two top circles
    int y_center = cy - r / 2;   // Vertical center offset for the circles
    int y_tip = cy + size - r;   // Bottom point of the heart

    // Centers of the two circles
    int x1 = cx - r;
    int x2 = cx + r;

    // Safety checks: ensure the heart fits on screen (optional, but good practice)
    if (y_center - r < 0 || y_tip >= SSD1306_HEIGHT) {
        // ESP_LOGW(TAG, "Heart too large or out of bounds!");
        return;
    }

    // 2. Draw the two filled circles (top lobes)
    ssd1306_fill_circle(buffer, x1, y_center, r, color);
    ssd1306_fill_circle(buffer, x2, y_center, r, color);

    // 3. Fill the small vertical gap between the two circles' bottom halves
    // This creates a continuous, solid top section.
    // Rect starts at (cx - r) and has width 2*r and height r (down to y_center + r)
    ssd1306_fill_rect(buffer, cx - r, y_center, 2 * r, r + 1, color);

    // 4. Draw and fill the bottom triangle using horizontal lines
    int y_start_fill = y_center + r;
    
    // Iterate from the bottom of the circles down to the tip
    for (int y = y_start_fill; y < y_tip; y++) {
        // Calculate the current horizontal line half-width based on its vertical position (y)
        // We use float arithmetic for smooth scaling, converting the integer difference to a fraction.
        float fraction_remaining = (float)(y_tip - y) / (y_tip - y_start_fill);
        
        // The line width starts at 'r' and shrinks down to 0 at the tip.
        int half_width = (int)(r * fraction_remaining);
        
        // Draw the horizontal line segment for the current row
        ssd1306_draw_line(buffer, cx - half_width, y, cx + half_width, y, color);
    }
}