#pragma once

#include <driver/i2c.h>
#include <esp_log.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <stdio.h>
#include "ssd1306.h"
#include "assets/face.h"
#include "mpu6050.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "esp_timer.h"
#include "shared.h"

// --- SSD1306 Commands and Constants ---
#define SSD1306_WIDTH          128
#define SSD1306_HEIGHT         64
#define SSD1306_CMD_MODE       0x00     // Co = 0, D/C = 0
#define SSD1306_DATA_MODE      0x40     // Co = 0, D/C = 1

// Full list of initialization commands for a 128x64 display
static const uint8_t init_cmds[] = {
    0xAE,          // 0xAE: Display OFF
    0xD5, 0x80,    // 0xD5: Set Display Clock Divide Ratio / Oscillator Frequency
    0xA8, 0x3F,    // 0xA8: Set Multiplex Ratio (63 for 64 height)
    0xD3, 0x00,    // 0xD3: Set Display Offset (no offset)
    0x40,          // 0x40: Set Start Line (line 0)
    0x8D, 0x14,    // 0x8D: Charge Pump Setting (VCC generated by internal DC/DC)
    0x20, 0x00,    // 0x20: Set Memory Addressing Mode (Horizontal Addressing Mode)
    0xA1,          // 0xA1: Set Segment Re-map (Horizontal flip)
    0xC8,          // 0xC8: Set COM Output Scan Direction (Vertical flip)
    0xDA, 0x12,    // 0xDA: Set COM Pins Hardware Configuration
    0x81, 0xCF,    // 0x81: Set Contrast Control
    0xD9, 0xF1,    // 0xD9: Set Pre-charge Period
    0xDB, 0x40,    // 0xDB: Set VCOMH Deselect Level
    0xA4,          // 0xA4: Entire Display ON (A5: All pixels ON)
    0xA6,          // 0xA6: Normal Display (A7: Inverse Display)
    0x2E,          // 0x2E: Deactivate Scroll
    0xAF           // 0xAF: Display ON
};

// Simple 8x8 font data for 'H', 'E', 'L', 'O', ',', ' ', 'E', 'S', 'P', '3', '2', '!'
// Each character is 8 bytes (1 page column)

#include "assets/font.h"

// Helper function to map ASCII characters to the custom font array index
int char_to_font_index(char c) {
    return c; // Default to space
}

#define SSD1306_I2C_ADDR 0x3C

/**
 * @brief Send a command to the SSD1306.
 * The command byte is sent right after the Control Byte (0x00 for command mode).
 */
static esp_err_t ssd1306_send_command(uint8_t command) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    
    // Address + Write Bit
    i2c_master_write_byte(cmd, (SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true); 
    
    // Control Byte: Command Mode (0x00)
    i2c_master_write_byte(cmd, SSD1306_CMD_MODE, true);
    
    // Command Byte
    i2c_master_write_byte(cmd, command, true);
    
    i2c_master_stop(cmd);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, cmd, 100 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
    return ret;
}

/**
 * @brief Send a block of data to the SSD1306 GDDRAM.
 * The data block is preceded by the Control Byte (0x40 for data mode).
 */
static esp_err_t ssd1306_send_data(const uint8_t *data, size_t len) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    
    // Address + Write Bit
    i2c_master_write_byte(cmd, (SSD1306_I2C_ADDR << 1) | I2C_MASTER_WRITE, true);
    
    // Control Byte: Data Mode (0x40)
    i2c_master_write_byte(cmd, SSD1306_DATA_MODE, true);
    
    // Data Block
    i2c_master_write(cmd, (uint8_t *)data, len, true);
    
    i2c_master_stop(cmd);
    esp_err_t ret = i2c_master_cmd_begin(I2C_MASTER_NUM, cmd, 100 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
    return ret;
}


/**
 * @brief Initialize the SSD1306 with the necessary command sequence.
 */
static esp_err_t ssd1306_init(void) {
    ESP_LOGI(TAG, "Starting SSD1306 initialization...");
    esp_err_t ret = ESP_OK;
    for (int i = 0; i < sizeof(init_cmds); i++) {
        // Some commands are two bytes long (command + argument), 
        // they are already grouped in the init_cmds array.
        if (ret != ESP_OK) break;
        ret = ssd1306_send_command(init_cmds[i]);
    }
    if (ret == ESP_OK) {
        ESP_LOGI(TAG, "SSD1306 initialized successfully.");
    } else {
        ESP_LOGE(TAG, "SSD1306 initialization failed: %s", esp_err_to_name(ret));
    }
    return ret;
}

/**
 * @brief Clears the entire GDDRAM by sending zeroed data to all pages.
 */
static esp_err_t ssd1306_clear(void) {
    esp_err_t ret = ESP_OK;
    
    // The screen is 8 pages high (64 pixels / 8 bits per page = 8 pages)
    for (uint8_t page = 0; page < (SSD1306_HEIGHT / 8); page++) {
        // 1. Set Page Address (0xB0 | page_num)
        ret = ssd1306_send_command(0xB0 | page); 
        if (ret != ESP_OK) return ret;

        // 2. Set Lower Column Start Address (0x00)
        ret = ssd1306_send_command(0x00);
        if (ret != ESP_OK) return ret;

        // 3. Set Higher Column Start Address (0x10)
        ret = ssd1306_send_command(0x10);
        if (ret != ESP_OK) return ret;
        
        // Create an array of 128 zero bytes for one page
        uint8_t clear_page_data[SSD1306_WIDTH] = {0}; 
        
        // 4. Send the 128 zero bytes to clear the page
        ret = ssd1306_send_data(clear_page_data, SSD1306_WIDTH);
        if (ret != ESP_OK) return ret;
    }
    return ESP_OK;
}

/**
 * @brief Writes a string to the display starting at a specific page (row) and column.
 * It uses the simple 8x8 font defined above.
 * @param str The string to display.
 * @param page The starting page (0-7 for 64-pixel height).
 * @param col The starting column (0-127).
 */
static esp_err_t ssd1306_write_text(const char *str, uint8_t page, uint8_t col) {
    esp_err_t ret = ESP_OK;
    if (page >= (SSD1306_HEIGHT / 8)) return ESP_FAIL; // Invalid page

    // 1. Set Page Address (row)
    ret = ssd1306_send_command(0xB0 | page); 
    if (ret != ESP_OK) return ret;

    // 2. Set Column Address (col)
    // The column address is split into lower (0x00-0x0F) and higher (0x10-0x1F) nibbles
    ret = ssd1306_send_command(0x00 | (col & 0x0F));     // Lower nibble of column start address
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0x10 | (col >> 4));      // Higher nibble of column start address
    if (ret != ESP_OK) return ret;

    // 3. Write data for each character
    for (const char *p = str; *p; p++) {
        int index = char_to_font_index(*p);
        const uint8_t *char_data = font8x8[index];
        // Each character is 8 bytes of data (one column in GDDRAM)
        ret = ssd1306_send_data(char_data, 8); 
        if (ret != ESP_OK) return ret;
    }
    return ESP_OK;
}

static esp_err_t ssd1306_draw_buffer(const uint8_t *buffer) {
    esp_err_t ret = ESP_OK;

    // 1. Set Column Address Range (0 - 127)
    // This tells the SSD1306 to treat the next data as columns 0 through 127
    ret = ssd1306_send_command(0x21); 
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0);    // Start Column
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(127);  // End Column
    if (ret != ESP_OK) return ret;

    // 2. Set Page Address Range (0 - 7)
    // This tells the SSD1306 to treat the next data as pages 0 through 7
    ret = ssd1306_send_command(0x22); 
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(0);    // Start Page
    if (ret != ESP_OK) return ret;
    ret = ssd1306_send_command(7);    // End Page
    if (ret != ESP_OK) return ret;

    // 3. Send the buffer in chunks
    // We send 1024 bytes. We could try sending it all at once, but I2C hardware 
    // buffers usually prefer smaller chunks. We will send 128 bytes (1 page) at a time.
    for (int i = 0; i < 1024; i += 128) {
        ret = ssd1306_send_data(&buffer[i], 128);
        if (ret != ESP_OK) return ret;
    }

    return ESP_OK;
}